#!/usr/bin/env bash
rm rollouts/*
if [[ "$RESUME" != 1 ]]; then
rm saved_rollouts/*
rm ai/*.json
rm models/*
rm metrics/*
rm gifs/*
rm logs/*
rm public/gifs/*
rm public/*.png
for AI in $AIS
do
echo $AI
../bin/overmind create models/$AI.model
export JOBS=${JOBS:-2}
envsubst < ai_templates/$AI.json > ai/$AI.json
cp models/$AI.model models/$AI.0.model
echo "$AI done"
done
fi
DEBUG=yes NO_CUDA=1 node nodemind.js
